### ISSUE TITLE
How to specify the version of Ensembl Genomes not the main Ensembl database

### ISSUE THREAD

**Issue by altairwei** [jorainer/ensembldb#108]
Ensembl Genomes database includes genome data for bacteria, fungi, invertebrate metazoa, plants, and protists. It's release version is different from main Ensembl database.

In order to make plant annotation packages, I have to use `fetchTablesFromEnsembl(101, host = "mysql-eg-publicsql.ebi.ac.uk", port = 4157, species = "triticum aestivum")` instead of `fetchTablesFromEnsembl(48, host = "mysql-eg-publicsql.ebi.ac.uk", port = 4157, species = "triticum aestivum")`. Otherwise I'll get this error:

https://github.com/jorainer/ensembldb/blob/388f139ec3b1e1908f477bb24b5b4326842e49ea/inst/perl/get_gene_transcript_exon_tables.pl#L106

However, `48` is the real version for EnsemblPlants. So I don't know what version of annotation package I'm creating.

**Comment by jorainer** [comment]
Hi @altairwei , the databases from ensemblgenomes 48 work with the ensembl perl API version 101 (see also in the [release notes](https://www.ensembl.info/category/01-release/)). Thus you have to make sure you have the latest Perl API version installed (i.e. 101) to generate `EnsDb` databases for Ensemblgenomes version 48. Your first call was thus correct.

**Comment by altairwei** [comment]
Thank you very much for your reply!
