### ISSUE TITLE
ensDbFromGtf does not read uncompressed files: Error in UseMethod("close")

### ISSUE THREAD

**Issue by egaffo** [jorainer/ensembldb#117]
Reading a GTF in plain text fails with the following error

```
ensDbFromGtf("Homo_sapiens.GRCh38.97.gtf")
Importing GTF file ... OK
Error in UseMethod("close") :
  no applicable method for 'close' applied to an object of class "character"
```
No errors when the same file was Gzipped

Tried with `ensembldb` v2.16.0 and 2.17.0

**Comment by jorainer** [comment]
can you please provide the output from calling `sessionInfo()`? I guess there might be an error in a downstream package as `ensembldb` uses `rtracklayer` to import gtf files.

**Comment by jorainer** [comment]
Ah, no, sorry. Indeed, there seems to be a problem in `ensembldb`. I will fix that. Thanks for reporting!

**Comment by jorainer** [comment]
versions 2.16.1 and 2.17.1 (will be available through BioC in the next couple of days) should fix this problem.

Closing the issue. Feel free to re-open if necessary.
