### ISSUE TITLE
Ensembl release 104

### ISSUE THREAD

**Issue by guidohooiveld** [jorainer/ensembldb#118]
Hi Johannes,
I don't know whether it is appropriate to ask here (if not, please close/delete my question), but I kindly would like to know if you plan to add `EnsDb` databases of release 104 to the annotation hub. Reason I am asking is that the latest GENCODE released for both human and mouse are based on/aligned with ENSEMBL release 104.
Thanks,
Guido

**Comment by jorainer** [comment]
Hi Guido! Sure, this is the right place to ask, and sorry, I completely forgot to create the `EnsDb`s for Ensembl 104. I started the scripts right now and will add them to `AnnotationHub`. This will take a couple of days, but I'm on it.

Thanks for the reminder!

**Comment by jorainer** [comment]
Release 104 `EnsDb`s are now available:

```r
> library(AnnotationHub)
> ah <- AnnotationHub()
snapshotDate(): 2021-05-18
> query(ah, "EnsDb")
AnnotationHub with 2719 records
# snapshotDate(): 2021-05-18
# $dataprovider: Ensembl
# $species: Homo sapiens, Xiphophorus maculatus, Xenopus tropicalis, Vicugna...
# $rdataclass: EnsDb
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH53185"]]' 

            title                                       
  AH53185 | Ensembl 87 EnsDb for Anolis Carolinensis    
  AH53186 | Ensembl 87 EnsDb for Ailuropoda Melanoleuca 
  ...       ...                                         
  AH95888 | Ensembl 104 EnsDb for Zonotrichia albicollis
  AH95889 | Ensembl 104 EnsDb for Zalophus californianus
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] AnnotationHub_3.0.1 BiocFileCache_2.0.0 dbplyr_2.1.1       
[4] BiocGenerics_0.38.0

loaded via a namespace (and not attached):
 [1] KEGGREST_1.32.0               tidyselect_1.1.1             
 [3] BiocVersion_3.13.1            purrr_0.3.4                  
 [5] vctrs_0.3.8                   generics_0.1.0               
 [7] htmltools_0.5.1.1             stats4_4.1.0                 
 [9] yaml_2.2.1                    utf8_1.2.1                   
[11] interactiveDisplayBase_1.30.0 blob_1.2.2                   
[13] rlang_0.4.11                  pillar_1.6.1                 
[15] later_1.2.0                   withr_2.4.2                  
[17] glue_1.4.2                    DBI_1.1.1                    
[19] rappdirs_0.3.3                bit64_4.0.5                  
[21] GenomeInfoDbData_1.2.6        lifecycle_1.0.0              
[23] zlibbioc_1.38.0               Biostrings_2.60.1            
[25] memoise_2.0.0                 Biobase_2.52.0               
[27] IRanges_2.26.0                fastmap_1.1.0                
[29] httpuv_1.6.1                  GenomeInfoDb_1.28.1          
[31] curl_4.3.2                    fansi_0.5.0                  
[33] AnnotationDbi_1.54.1          Rcpp_1.0.7                   
[35] xtable_1.8-4                  promises_1.2.0.1             
[37] filelock_1.0.2                BiocManager_1.30.16          
[39] cachem_1.0.5                  S4Vectors_0.30.0             
[41] XVector_0.32.0                mime_0.11                    
[43] bit_4.0.4                     png_0.1-7                    
[45] digest_0.6.27                 dplyr_1.0.7                  
[47] shiny_1.6.0                   tools_4.1.0                  
[49] bitops_1.0-7                  magrittr_2.0.1               
[51] RCurl_1.98-1.3                tibble_3.1.2                 
[53] RSQLite_2.2.7                 crayon_1.4.1                 
[55] pkgconfig_2.0.3               ellipsis_0.3.2               
[57] rstudioapi_0.13               assertthat_0.2.1             
[59] httr_1.4.2                    R6_2.5.0                     
[61] compiler_4.1.0               

```

I'm closing this issue now. Feel free to re-open if necessary.

**Comment by guidohooiveld** [comment]
Thanks Jo! Already using mouse Ensembl release 104!

**Comment by guidohooiveld** [comment]
Hi Jo,
If your time permits, would it be possible to add the human and mouse Ensembl release 106 `EnsDb`s to the annotation hub? I am asking for the reason above (updated GENCODE), but also because I am somehow not able to generate the` EnsDb`s myself on my own system (likely because of a PERL incompatibility).

Again, thanks a lot!
G

https://www.ensembl.info/2022/04/12/ensembl-106-has-been-released/

**Comment by jorainer** [comment]
Hi Guido,

Ensembl 106 `EnsDb` are already on `AnnotationHub`, but only for BioC >= 3.15 (maybe that's why you haven't found them yet):

```r
> library(AnnotationHub)
> ah <- AnnotationHub()
snapshotDate(): 2022-04-21
> query(ah, "EnsDb.Hsapiens.v106")
AnnotationHub with 1 record
# snapshotDate(): 2022-04-21
# names(): AH100643
# $dataprovider: Ensembl
# $species: Homo sapiens
# $rdataclass: EnsDb
# $rdatadateadded: 2022-04-21
# $title: Ensembl 106 EnsDb for Homo sapiens
# $description: Gene and protein annotations for Homo sapiens based on Ensem...
# $taxonomyid: 9606
# $genome: GRCh38
# $sourcetype: ensembl
# $sourceurl: http://www.ensembl.org
# $sourcesize: NA
# $tags: c("106", "Annotation", "AnnotationHubSoftware", "Coverage",
#   "DataImport", "EnsDb", "Ensembl", "Gene", "Protein", "Sequencing",
#   "Transcript") 
# retrieve record with 'object[["AH100643"]]' 
```

Thanks for reminding me - could well be that I miss an Ensembl release. So, let me know whenever something is missing.

cheers, jo

**Comment by guidohooiveld** [comment]
Yep, you are completely right! How silly from me... 

Just updated to R-4.2.0/BioC-3.15 (from R-4.1.2/BioC-3.14), and found `EnsDb.Hsapiens.v106`.

Once more, thanks a lot for continuous work to keep the `EnsDb`s up-to-date!

G

**Comment by guidohooiveld** [comment]
Hi Johannes,
Just kindly asking whether the release 114 `EnsDb` for human and mouse are already available on the `annotationHub`?

I am asking because release 114 is corresponding to the latest release of GENCODE (= 48 / M37), and I cannot find the v114 files (release 113 seems to be the latest).

Thanks,
G

 ```
> AnnotationHub::query(ah, pattern = c("EnsDb","Homo sapiens", "GRCh38"))
AnnotationHub with 28 records
# snapshotDate(): 2025-04-08
# $dataprovider: Ensembl
# $species: Homo sapiens
# $rdataclass: EnsDb
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH53211"]]' 

             title                             
  AH53211  | Ensembl 87 EnsDb for Homo Sapiens 
  AH53715  | Ensembl 88 EnsDb for Homo Sapiens 
  AH56681  | Ensembl 89 EnsDb for Homo Sapiens 
  AH57757  | Ensembl 90 EnsDb for Homo Sapiens 
  AH60773  | Ensembl 91 EnsDb for Homo Sapiens 
  ...        ...                               
  AH109606 | Ensembl 109 EnsDb for Homo sapiens
  AH113665 | Ensembl 110 EnsDb for Homo sapiens
  AH116291 | Ensembl 111 EnsDb for Homo sapiens
  AH116860 | Ensembl 112 EnsDb for Homo sapiens
  AH119325 | Ensembl 113 EnsDb for Homo sapiens
> 
```

**Comment by jorainer** [comment]
Hi @guidohooiveld , sorry, no, I did not create the release 114 databases. We're also discussing at Bioconductor whether it's feasible to actually continue providing the databases for all species. I could create selected databases upon request - however, I'm on a conference now and then on holidays :( - so it would need some time...

**Comment by guidohooiveld** [comment]
Thanks for clarifying!

Yes, I fully understand the burden on you/the resources that are needed to continuously provide all `EnsDb` versions on the `AnnotationHub`.

If you ask me: a good choice could be to standard provide an `EnsDb` for the same species an (NCBI-based) `OrgDb` is made, since I guess that covers > 95% of the use cases. That would then also include human and mouse (= species GENCODE); the species I work almost exclusively with.  :)

**Comment by jorainer** [comment]
Thanks Guido, that's an excellent idea. I will discuss with the Bioconductor core people.

**Comment by jorainer** [comment]
So, for now I added the `EnsDb`'s for some species for Ensembl release 114 to dropbox: https://www.dropbox.com/scl/fo/amew3myrgxx28uomk9e7g/ABPObLuXj_Do4v8ngC515Qg?rlkey=t8eyrjeraokxgunpvkrh4oc31&st=e5vp1a06&dl=0 - I'll also add them to *AnnotationHub* once we have decided how we want to go from here (i.e. how to select *relevant* species)

**Comment by jorainer** [comment]
Also, I have created now a docker image that allows to build `EnsDb` SQLite databases for any species: https://github.com/jorainer/ensdb_docker

**Comment by guidohooiveld** [comment]
Thanks for providing the files, Jo!

Also nice that you created a docker image! This allows for flexibility for users, and will also reduce your workload! Hope to test it soon.

**Comment by guidohooiveld** [comment]
For the archive: I made a post at the GitHub of `ensdb_docker` to show how I used the docker to make an `EnsDb` myself.

https://github.com/jorainer/ensdb_docker/issues/1
