### ISSUE TITLE
Older Version of Ensembldb with R > 4.0

### ISSUE THREAD

**Issue by rbenel** [jorainer/ensembldb#120]
I have been using the EnsDb.Hsapiens.v92 for my annotations for the past few years; however, this past week I updated R to 4.1 and the package is no longer compatible..

Any ideas what I can do to fix this? I would like to be consistent in my research and continue using the same version, EnsDb.Hsapiens.v92.

This is the error I receive.

```
Error: package or namespace load failed for 'EnsDb.Hsapiens.v92':
 package 'EnsDb.Hsapiens.v92' was installed before R 4.0.0: please re-install it--"
```

**Comment by jorainer** [comment]
Dear @rbenel , I would suggest to retrieve EnsDbs always from `AnnotationHub` as they will always be available there (and I will add databases for upcoming Ensembl releases).

**Comment by rbenel** [comment]
Yes, thanks for the response. 
In case anyone encounters the same issue, here is one possible solution I posted on Bioconductor. 
https://support.bioconductor.org/p/9139007/#9139018
