### ISSUE TITLE
Add protein data

### ISSUE THREAD

**Issue by jorainer** [jorainer/ensembldb#14]
What about adding protein annotations to `ensembldb`. @lgatto might that be something in your interest too?

**Comment by lgatto** [comment]
Yes, that would be _very_ useful. That's something that was on my todo list! See the [`Pbase` mapping vignette](http://bioconductor.org/packages/devel/bioc/vignettes/Pbase/inst/doc/mapping.html) for a use-case. 
Also, I know that UniProt have done some ENS to UniProt mapping, but I am not sure if it has been released yet. Happy to discuss here and contribute.

**Comment by jorainer** [comment]
Seeing that you're already using biomart there should be no problem. I'll check if I can find the right data in the Ensembl servers.

**Comment by lgatto** [comment]
I think, it would be useful to have 2 parallel solutions; one that relies on up-to-date mapping using queries, and one that provides pre-mapped identifiers (for traceability and reproducibility). If the data is available on the Ensembl servers and it is versioned, then we git two birds with one stone.

**Comment by jorainer** [comment]
An update: I can get the following information from Ensembl:
- Ensembl protein ID for each (coding) transcript. For some there is a n:1 mapping between transcript and protein, i.e. when the coding region of the transcripts is identical.
- Uniprot ID for (most) Ensembl protein IDs (with an n:1 mapping).
- peptide sequence (after applying eventual RNA edits).
- Protein domains for each Ensembl protein ID along with start/end within the peptide sequence, the source (_pfam_, _scanprosite_, _prints_ etc), interpro accession.

@lgatto what data do you think you might need or like to have? Do you think that's enough? I think with this data, along with the genomic transcript and exon coordinates it should be possible also to map e.g. protein domains to the genome.

**Comment by jorainer** [comment]
Protein data is now included. Now it's matter of how to best extract and represent the data.
