### ISSUE TITLE
Best way to represent the protein data

### ISSUE THREAD

**Issue by jorainer** [jorainer/ensembldb#20]
Extracting the protein annotations in form of a `data.frame` and `DataFrame` is straight forward, the question however is what type of object could _best_ represent the protein annotation.

The object should be something similar to a `GRanges`, eventually the `Proteins` class from the `Pbase` (https://github.com/ComputationalProteomicsUnit/Pbase) package?

I've got:
- (Ensembl) protein ID with sequence.
- 1:n mapping of protein ID to Uniprot ID.
- n:m mapping between protein ID and protein domain ID, which provides in addition the position of the protein domain within the protein sequence.

@lgatto any suggestions/preferences here?

**Comment by lgatto** [comment]
I would have thought `Proteins` would have been the best choice, but given the [circular dependency](https://github.com/jotsetung/ensembldb/issues/20), this might not be an option. But maybe something more low-level will suffice, and we can then make use of it.

Do you want a single data structure for all the points above? 

What do you mean by _protein domain ID_? Functional domains, or transcript exons start/end sites?

**Comment by jorainer** [comment]
regarding the _protein domain ID_: from Ensembl I get for each protein coding transcript its _translation_, which is in fact a protein sequence (AA) along with its ID (the Ensembl `protein_id`). For each `protein_id` I can then fetch the Uniprot ID (which can be none, 1 or more) and I fetch all protein domains from the various sources (Pfam, prosite, Smart); these have then start and end coordinates on the AA-sequence of the protein. That's why I thought `Proteins` might be a good data structure, as it allows to add to each AA-sequence also features on this sequence.

In a first version I will return protein results from the database as a `AAStringSet` with all additional annotations in the `mcols`.

**Comment by lgatto** [comment]
Fantastic! Let me know when this becomes available and I will update `Pbase` to make use of it.
