### ISSUE TITLE
Problem importing Pbase

### ISSUE THREAD

**Issue by jorainer** [jorainer/ensembldb#21]
I am trying to import the `Proteins` class, but as soon as I import anything from https://github.com/ComputationalProteomicsUnit/Pbase I get the following error:

```
* installing *source* package ‘ensembldb’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  cyclic namespace dependency detected when loading ‘ensembldb’, already loading ‘biovizBase’, ‘Gviz’, ‘Pbase’, ‘ensembldb’
ERROR: lazy loading failed for package ‘ensembldb’
* removing ‘/Users/jo/R/R-3.3.1-Bioc3.4-devel/lib/R/library/ensembldb’
* restoring previous ‘/Users/jo/R/R-3.3.1-Bioc3.4-devel/lib/R/library/ensembldb’
```

**Comment by jorainer** [comment]
apparently that problem is not really specific:
http://blog.nextbiomotif.com/2014/04/curious-cyclic-namespace-dependency.html
https://gist.github.com/anonymous/10018579
http://r.789695.n4.nabble.com/changes-in-recent-R-devel-revisions-td3330790.html

... could be anything.

**Comment by jorainer** [comment]
Nope, it's pretty clear: `Pbase` imports `Gviz` which imports `biovizBase` which imports `ensembldb`.
Thinking it all over it also does not really sense to use the `Proteins` objects, eventually it will be better to _just_ return a `AAStringSet`.

**Comment by lgatto** [comment]
Is there now way around such circular dependencies? An `if` statement in `.onLoad`, of something like that?

**Comment by jorainer** [comment]
In the end I don't think it makes much sense to import `Pbase` into `ensembldb` as `ensembldb` is supposed to provide _only_ the annotation, and `Pbase` is supposed to use that annotation and make sense of it.
