### ISSUE TITLE
ensembldb query backend

### ISSUE THREAD

**Issue by lgatto** [jorainer/ensembldb#31]
Based on a brainstorming chat with UniProt:
- Do you use the UniProt RESTful API to get the data? 
- I think you use the Ensembl perl API?

From the conversation, there are differences in the Ens -> Uniprot and Uniprot -> Ens mapping. But when these agree, then the features will match; but some features exist in one and not other. 

To be discussed at EuroBioc in Basel.

**Comment by jorainer** [comment]
I am using only the Ensembl perl API - don't know how exactly they map their Ensembl protein IDs with the Uniprot IDs, but I *trust* them that what they're doing is OK.

Yes, there are Ensembl protein IDs that are not mapped to Uniprot IDs. There are also Ensembl protein IDs assigned to transcripts that are targeted to nonsense mediated mRNA decay and thus - under normal circumstances - will not be translated at all (although in theory these have a CDS).

**Comment by lgatto** [comment]
Thanks for the clarification.
