### ISSUE TITLE
Missing GenomeInfoDbData

### ISSUE THREAD

**Issue by mjsteinbaugh** [jorainer/ensembldb#63]
Hi Johannes,

I think there's a package import issue with the latest version of GenomeInfoDb and GenomeInfoDbData. If you run `biocLite("ensembldb")` on a clean R installation with Bioconductor 3.6, ensembldb fails to load because GenomeInfoDbData doesn't get installed. But looking at the [GenomeInfoDb](https://bioconductor.org/packages/release/bioc/html/GenomeInfoDb.html) imports, GenomeInfoDbData is listed there, so I'm not entirely sure what's causing this issue. Any ideas?

This also happens for me with the GitHub version of ensembldb on a clean R installation.

Best,
Mike

**Comment by jorainer** [comment]
Thanks for reporting! I'll have a look.

**Comment by mjsteinbaugh** [comment]
Great thanks! Actually, running `biocLite("ensembldb")` on a clean install works. I seem to be running into an issue when adding ensembldb as an import for a GitHub package. `biocLite()` doesn't seem to install the GenomeInfoDb and GenomeInfoDbData dependencies correctly when using `devtools::install_github()`.

**Comment by jorainer** [comment]
Strange - I've just compiled R-3.4.2 from source and ran
```r
source("https://bioconductor.org/biocLite.R")
biocLite("ensembldb")
```
and it worked without problem (I'm on macOS 10.13.1).

I'll try next with `devtools::install_github`.

**Comment by mjsteinbaugh** [comment]
Yeah I think the problem I'm running into is when importing ensembldb as a dependency inside a package. For some reason GenomeInfoDbData doesn't get installed with the `install_github()` call.

**Comment by mjsteinbaugh** [comment]
On a clean install this fails and causes ensembldb to also fail, when trying to install from GitHub:

```r
devtools::install_github("Bioconductor/GenomeInfoDb")
```

Here's the error:

```
ERROR: dependency ‘GenomeInfoDbData’ is not available for package ‘GenomeInfoDb’
```

I'll see if I can patch GenomeInfoDb to install correctly from GitHub.
