### ISSUE TITLE
heavyweight dependencies

### ISSUE THREAD

**Issue by lawremi** [jorainer/ensembldb#66]
Would it be feasible to move AnnotationHub and RMySQL to Suggests? I had to install MySQL with homebrew to install RMySQL, so it's a bit of a pain. AnnotationHub depends on stuff like shiny, which is also giving me problems right now.

**Comment by jorainer** [comment]
good point! thanks @lawremi , I'll do.

**Comment by jorainer** [comment]
OK, there is unfortunately not much I can do - I'm importing stuff from `AnnotationHub`, so I'll need to keep that in Imports. `RMySQL` was already in Enhances - strange that it required you to install that. I had `shiny` in Suggests and moved that now to Enhances in version 2.3.3.

**Comment by lawremi** [comment]
I'll have to figure out why ggbio depends on RMySQL. I don't think the method and class imports of AnnotationHub are strictly required. You could probably get away with a Suggests.

**Comment by jorainer** [comment]
Moved `AnnotationHub` from Imports to Suggests now. Hope it reduces the amount of required package installations.

**Comment by lawremi** [comment]
Awesome, thanks a lot.
