### ISSUE TITLE
Get the Swissprot IDs

### ISSUE THREAD

**Issue by jorainer** [jorainer/ensembldb#71]
As @the-x-at suggested we should try to get/provide also the Swissprot IDs (Uniprot Acc) for each protein.

**Comment by jorainer** [comment]
Seems to be tricky, as the information seems not to be present in the ensembl core database.

**Comment by the-x-at** [comment]
To be precise, ensembldb currently returns an entity named "uniprot_id", which is what UniProt calls "entry name". UniProt lingo differentiates between "UniProt accession number" and "UniProt entry name". The former is stable, the latter is subject to change - P69905 versus HBA_HUMAN. More info can be found in the UniProt help pages:
http://www.uniprot.org/help/difference_accession_entryname
http://www.uniprot.org/help/accession_numbers
http://www.uniprot.org/help/entry_name

One example is given by UniProt accession number Q8IVT2. This used to be Uniprot entry name CS021_HUMAN in release 2013_06 and has become MISP_HUMAN in release 2013_08. See the protein's history on UniProt: http://www.uniprot.org/uniprot/Q8IVT2?diff=true&version=78&version=79

**Comment by jorainer** [comment]
In more recent Ensembl core databases this seems to be fixed and the Uniprot accession is provided:

```r
library(BiocInstaller)
biocLite("EnsDb.Hsapiens.v86")
library(EnsDb.Hsapiens.v86)
edb <- EnsDb.Hsapiens.v86

proteins(edb, filter = ~ genename == "MISP", columns = c("protein_id", "uniprot_id"))
DataFrame with 1 row and 3 columns
       protein_id  uniprot_id   gene_name
      <character> <character> <character>
1 ENSP00000215582      Q8IVT2        MISP

```

While with older Ensembl versions we got:
```r
library(EnsDb.Hsapiens.v75)
edb <- EnsDb.Hsapiens.v75
proteins(edb, filter = ~ genename == "MISP", columns = c("protein_id", "uniprot_id"))
DataFrame with 1 row and 3 columns
       protein_id  uniprot_id   gene_name
      <character> <character> <character>
1 ENSP00000215582  MISP_HUMAN        MISP
```
I'll update `ensembldb` to use `EnsDb.Hsapiens.v86` instead of the fairly old `EnsDb.Hsapiens.v75`.

**Comment by jorainer** [comment]
There's no fix for older Ensembl versions, but the new ones are OK.
