### ISSUE TITLE
Get the amoniacid name for each positition

### ISSUE THREAD

**Issue by Tato14** [jorainer/ensembldb#80]
Hi! Great tool!

I was wondering if is there a way that `genomeToProtein` could add the translated aminoacid sequence of the nucleotides that are in the genomic range.

Thanks!

**Comment by jorainer** [comment]
This should be possible since the amino acid sequences are also available in the `EnsDb` database. Could you provide a simple working example of mapping for which you would like to get the amino acid sequence? I can then work on that to see how that can be done efficiently.

**Comment by Tato14** [comment]
You mean a genomic coordinate? Try this one: chr1:162724414-162724421

I'm using hg19 so I guess you should use EnsDb.Hsapiens.v75.

If this is a big issue I could manage to get de DNA sequence and, from there, I could translate it but would be great to do it in the same command :)

Thanks!

**Comment by jorainer** [comment]
Thanks for the example. I'll have a look at it and report back.

**Comment by jorainer** [comment]
To get the amino acids for the specified genomic region:

First we map the genomic positions to positions within the amino acid sequence of the respective proteins encoded on the genomic region:
```r
library(ensembldb)
library(EnsDb.Hsapiens.v75)

edb <- EnsDb.Hsapiens.v75

## Change to UCSC chromosome naming
seqlevelsStyle(edb) <- "UCSC"

## Define the genomic region of interest
grg <- GRanges("chr1:162724414-162724421")

## Map the coordinates to protein-relative coordinates
prt <- genomeToProtein(grg, edb)
prt
IRangesList of length 1
[[1]]
IRanges object with 4 ranges and 8 metadata columns:
                      start       end     width |           tx_id    cds_ok
                  <integer> <integer> <integer> |     <character> <logical>
  ENSP00000356898        62        65         4 | ENST00000367921      TRUE
  ENSP00000356899        62        65         4 | ENST00000367922      TRUE
  ENSP00000391310        62        65         4 | ENST00000415555     FALSE
  ENSP00000400309        62        65         4 | ENST00000446985     FALSE
                          exon_id exon_rank seq_start   seq_end    seq_name
                      <character> <integer> <integer> <integer> <character>
  ENSP00000356898 ENSE00001165686         5 162724414 162724421        chr1
  ENSP00000356899 ENSE00001165686         6 162724414 162724421        chr1
  ENSP00000391310 ENSE00001165686         5 162724414 162724421        chr1
  ENSP00000400309 ENSE00001625769         5 162724414 162724421        chr1
                   seq_strand
                  <character>
  ENSP00000356898           *
  ENSP00000356899           *
  ENSP00000391310           *
  ENSP00000400309           *

```

What you might realize, the lengths of the genomic region and amino acid sequences do not really match:
```r
> width(grg)
[1] 8
> width(unlist(prt))
[1] 4 4 4 4
```

so, while we have 8 nucleotides, these map to 4 amino acids. Considering that 3 nucleotides encode 1 amino acid this does not seem to fit. What happens here is that the we map each position within a codon to the respective amino acid, even if not all 3 nucleotides of the codon are provided.

Now, to get the respective amino acids:

```r
## Unlist the IRangesList into an IRanges, because we have only one.
prt <- unlist(prt)

## Get the protein sequences, return as AAStringSet so that we can apply all
## sequence related functions right away
prt_seq <- proteins(edb, filter = ~ protein_id == names(prt),
                    return.type = "AAStringSet")

library(Biostrings)
subseq(prt_seq, start = start(prt), end = end(prt))
  A AAStringSet instance of length 4
    width seq                                               names               
[1]     4 RLDS                                              ENSP00000356898
[2]     4 RLDS                                              ENSP00000356899
[3]     4 RLDS                                              ENSP00000391310
[4]     4 RLDS                                              ENSP00000400309
```

**Comment by Tato14** [comment]
Great! Thanks!
